### PR TITLE
Add icon

### PR DESCRIPTION
**Pull request by d-m-u**
Shamelessly stealing idea from carbonin (https://gitter.im/ManageIQ/manageiq/providers?at=5a8c814d6fba1a703a7b0261) per suggestion of jrafanie

### CODE REVIEW

**Comment by d-m-u** [comment]
@jrafanie something like this?

**Comment by syncrou** [comment]
@d-m-u - this is quite the arresting development.

**Comment by d-m-u** [comment]
@syncrou give it a rest, sister

**Comment by djberg96** [comment]
How will this actually be used? Does github pick it up somehow?

**Comment by d-m-u** [comment]
No, closing cause it needs to be different, need image in readme cause github doesn't actually do anything with icons :(. Will reopen a better one.

**Pull request closed without merging**
