### PR TITLE
Updated Codeclimate gem

### PR DESCRIPTION
**Pull request by juliancheal**
Fixes this issue https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions

- Added simplecov to spec helper
- Also added after script test to run codeclimate reporter

### CODE REVIEW

**Comment by bronaghs** [comment]
@juliancheal - the documentation talks about setting CODECLIMATE_REPO_TOKEN
Should we do that somewhere?

**Comment by Fryguy** [comment]
Since it's a hidden token, I set it in travis directly.

**Comment by bronaghs** [comment]
OK, then this LGTM 
@Fryguy - looks good to you?

**Comment by Fryguy** [comment]
@juliancheal I think we should also update the gemspec file with the version.. https://github.com/ManageIQ/azure-armrest/blob/825318b2f9d0420400d11ee3c7c2165c6349982c/azure-armrest.gemspec#L34

**Comment by juliancheal** [comment]
@Fryguy ah thanks, didn't think to check the gemspec too.

**Comment by juliancheal** [comment]
Is that really necessary though in the Gemspec as it's included in the Gemfile?

**Comment by Fryguy** [comment]
yeah, technically not necessary, but good to be complete.

**Pull request merged**
