### PR TITLE
Fix message bug

### PR DESCRIPTION
**Pull request by djberg96**
Seems I forgot an assignment operator.

### CODE REVIEW

**Comment by bronaghs** [comment]
So @djberg96  this could explain why we didnt see this message in the logs we discussed yesterday.

**Comment by djberg96** [comment]
@bronaghs it might!

**Comment by djberg96** [comment]
@bronaghs i should add that i would expect to see an exception regarding an "undefined method 'msg'" or something along those lines then.

**Comment by bronaghs** [comment]
True. I will wade through the logs again looking for it. If found, it would verify the timeout was rescued and could move the investigation forward.

**Pull request merged**
