### PR TITLE
Add SnapshotService

### PR DESCRIPTION
**Pull request by djberg96**
This adds a SnapshotService class. This is to keep up with Azure's move from individual storage accounts to managed disks.

### CODE REVIEW

**Comment by djberg96** [comment]
@bronaghs @bzwei Please review.

**Comment by bzwei** [comment]
@djberg96 Have you thought about adding a storage lay like `Azure::Armrest::Storage::AbcService`? Should we group all new services due to Azure's movement to managed disks to this folder?

**Comment by djberg96** [comment]
@bzwei I thought about putting it under a "ManagedDisk" namespace, since that's currently how the Azure docs organize it. I could see using "Storage" as well to be more generic, since MS could change the name.

**Comment by djberg96** [comment]
@bzwei Ok, I moved both Snapshot and Disk under the Storage namespace. I'll move Image after this is merged.

**Comment by bzwei** [comment]
LGTM. I guess the existing `StorageService` has not been widely used 😄

**Pull request merged**
