### PR TITLE
Mark some internal methods as private, update capture method

### PR DESCRIPTION
**Pull request by djberg96**
This marks a few of our internal methods as private, and updates the capture method.

### CODE REVIEW

**Comment by bzwei** [comment]
This is minor. In the future you may want to use a git pull/rebase command instead of merge, so that no more merge branch commits shown in the history.

**Comment by djberg96** [comment]
@bzwei Yep, I'm not sure how to fix this one, though.

**Comment by bzwei** [comment]
We can leave this one as is.

**Comment by bzwei** [comment]
:+1: LGTM

**Pull request merged**
